<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\BlogArticle;

class BlogArticlesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        BlogArticle::truncate();
        $records = [
            [
                'id'                             => '1',
                'blog_subcategory_id'            => '1',
                'blog_article_author'            => 'Adrian Dumitru',
                'blog_article_time'              => 11,
                'blog_article_title'             => 'First Article',
                'blog_article_short_description' => 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad eligendi nihil deserunt expedita eaque consequuntur dolores sed dolor a vel, fuga culpa! Cumque est animi vero voluptates dolorum nobis doloremque!',
                'blog_article_content_section_1' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_2' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_3' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_4' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_5' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_media_url'         => '',
                'blog_article_path'              => '/blog/article/view',
                'blog_article_is_active'         => '1',
                'created_at'                     => '2021-09-23 12:30:00',
                'updated_at'                     => '2021-09-23 12:45:00',
            ],
            [
                'id'                             => '2',
                'blog_subcategory_id'            => '2',
                'blog_article_author'            => 'Adrian Dumitru',
                'blog_article_time'              => 9,
                'blog_article_title'             => 'Second Article',
                'blog_article_short_description' => 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad eligendi nihil deserunt expedita eaque consequuntur dolores sed dolor a vel, fuga culpa! Cumque est animi vero voluptates dolorum nobis doloremque!',
                'blog_article_content_section_1' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_2' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_3' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_4' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_5' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_media_url'         => '',
                'blog_article_path'              => '/blog/article/view',
                'blog_article_is_active'         => '1',
                'created_at'                     => '2021-09-23 12:30:00',
                'updated_at'                     => '2021-09-23 12:45:00',
            ],
            [
                'id'                             => '3',
                'blog_subcategory_id'            => '3',
                'blog_article_author'            => 'Adrian Dumitru',
                'blog_article_time'              => 9,
                'blog_article_title'             => 'Third Article',
                'blog_article_short_description' => 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad eligendi nihil deserunt expedita eaque consequuntur dolores sed dolor a vel, fuga culpa! Cumque est animi vero voluptates dolorum nobis doloremque!',
                'blog_article_content_section_1' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_2' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_3' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_4' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_5' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_media_url'         => '',
                'blog_article_path'              => '/blog/article/view',
                'blog_article_is_active'         => '1',
                'created_at'                     => '2021-09-06 11:45:00',
                'updated_at'                     => '2021-09-06 11:45:00',
            ],
            [
                'id'                             => '4',
                'blog_subcategory_id'            => '4',
                'blog_article_author'            => 'Alina Vasile',
                'blog_article_time'              => 15,
                'blog_article_title'             => 'First Audio Article',
                'blog_article_short_description' => 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad eligendi nihil deserunt expedita eaque consequuntur dolores sed dolor a vel, fuga culpa! Cumque est animi vero voluptates dolorum nobis doloremque!',
                'blog_article_content_section_1' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_2' => '',
                'blog_article_content_section_3' => '',
                'blog_article_content_section_4' => '',
                'blog_article_content_section_5' => '',
                'blog_article_media_url'         => '',
                'blog_article_path'              => '/blog/audio/view',
                'blog_article_is_active'         => '1',
                'created_at'                     => '2021-09-11 00:00:00',
                'updated_at'                     => '2021-09-11 00:00:00',
            ],
            [
                'id'                             => '5',
                'blog_subcategory_id'            => '5',
                'blog_article_author'            => 'Alina Vasile',
                'blog_article_time'              => 5,
                'blog_article_title'             => 'Second Audio Article',
                'blog_article_short_description' => 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad eligendi nihil deserunt expedita eaque consequuntur dolores sed dolor a vel, fuga culpa! Cumque est animi vero voluptates dolorum nobis doloremque!',
                'blog_article_content_section_1' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_2' => '',
                'blog_article_content_section_3' => '',
                'blog_article_content_section_4' => '',
                'blog_article_content_section_5' => '',
                'blog_article_media_url'         => '',
                'blog_article_path'              => '/blog/audio/view',
                'blog_article_is_active'         => '1',
                'created_at'                     => '2021-09-12 00:00:00',
                'updated_at'                     => '2021-09-12 00:00:00',
            ],
            [
                'id'                             => '6',
                'blog_subcategory_id'            => '6',
                'blog_article_author'            => 'Alina Vasile',
                'blog_article_time'              => 25,
                'blog_article_title'             => 'Third Audio Article',
                'blog_article_short_description' => 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad eligendi nihil deserunt expedita eaque consequuntur dolores sed dolor a vel, fuga culpa! Cumque est animi vero voluptates dolorum nobis doloremque!',
                'blog_article_content_section_1' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_2' => '',
                'blog_article_content_section_3' => '',
                'blog_article_content_section_4' => '',
                'blog_article_content_section_5' => '',
                'blog_article_media_url'         => '',
                'blog_article_path'              => '/blog/audio/view',
                'blog_article_is_active'         => '1',
                'created_at'                     => '2021-09-13 00:00:00',
                'updated_at'                     => '2021-09-13 00:00:00',
            ],
            [
                'id'                             => '7',
                'blog_subcategory_id'            => '7',
                'blog_article_author'            => 'Popescu Marius',
                'blog_article_time'              => 7,
                'blog_article_title'             => 'First Video Article',
                'blog_article_short_description' => 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad eligendi nihil deserunt expedita eaque consequuntur dolores sed dolor a vel, fuga culpa! Cumque est animi vero voluptates dolorum nobis doloremque!',
                'blog_article_content_section_1' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_2' => '',
                'blog_article_content_section_3' => '',
                'blog_article_content_section_4' => '',
                'blog_article_content_section_5' => '',
                'blog_article_media_url'         => '',
                'blog_article_path'              => '/blog/video/view',
                'blog_article_is_active'         => '1',
                'created_at'                     => '2021-09-16 00:00:00',
                'updated_at'                     => '2021-09-16 00:00:00',
            ],
            [
                'id'                             => '8',
                'blog_subcategory_id'            => '8',
                'blog_article_author'            => 'Popescu Marius',
                'blog_article_time'              => 19,
                'blog_article_title'             => 'Second Video Article',
                'blog_article_short_description' => 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad eligendi nihil deserunt expedita eaque consequuntur dolores sed dolor a vel, fuga culpa! Cumque est animi vero voluptates dolorum nobis doloremque!',
                'blog_article_content_section_1' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_2' => '',
                'blog_article_content_section_3' => '',
                'blog_article_content_section_4' => '',
                'blog_article_content_section_5' => '',
                'blog_article_media_url'         => '',
                'blog_article_path'              => '/blog/video/view',
                'blog_article_is_active'         => '1',
                'created_at'                     => '2021-09-17 00:00:00',
                'updated_at'                     => '2021-09-17 00:00:00',
            ],
            [
                'id'                             => '9',
                'blog_subcategory_id'            => '9',
                'blog_article_author'            => 'Popescu Marius',
                'blog_article_time'              => 13,
                'blog_article_title'             => 'Third Video Article',
                'blog_article_short_description' => 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad eligendi nihil deserunt expedita eaque consequuntur dolores sed dolor a vel, fuga culpa! Cumque est animi vero voluptates dolorum nobis doloremque!',
                'blog_article_content_section_1' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'blog_article_content_section_2' => '',
                'blog_article_content_section_3' => '',
                'blog_article_content_section_4' => '',
                'blog_article_content_section_5' => '',
                'blog_article_media_url'         => '',
                'blog_article_path'              => '/blog/video/view',
                'blog_article_is_active'         => '1',
                'created_at'                     => '2021-09-23 12:30:00',
                'updated_at'                     => '2021-09-23 12:45:00',
            ],
        ];
        BlogArticle::insert($records);
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }
}
