<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\BlogSubcategory;

class BlogSubcategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        BlogSubcategory::truncate();
        $records = [
            [
                'id'                                 => '1',
                'blog_category_id'                   => '1',
                'blog_subcategory_title'             => 'Subcategoria A',
                'blog_subcategory_short_description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet accusantium rerum impedit nam, voluptate reprehenderit nemo expedita fuga, dicta sint eum ex delectus saepe debitis veniam recusandae perferendis illum optio!',
                'blog_subcategory_description'       => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius corporis velit enim animi. Reiciendis nesciunt libero magnam quaerat! Nulla, dolore sint deserunt quas iure sed magnam consectetur architecto eligendi iste? Dignissimos, velit, molestiae repellendus cupiditate nobis eos corporis ipsam possimus qui unde veritatis temporibus, dolorum saepe accusamus laudantium quibusdam iusto autem placeat eaque error quia provident dolore laboriosam minus? Fugit corrupti nam ex, officia sapiente aspernatur eos at suscipit eveniet quasi quisquam ea fugiat reprehenderit provident. Minima, laudantium exercitationem ducimus ratione natus tempore! Asperiores, consequuntur! Ad culpa nihil nemo magni iste, deserunt quis? Esse quia totam ea magni quas ipsam cumque minus officiis unde quos sapiente laboriosam debitis iste reiciendis beatae ut vel perspiciatis quisquam aperiam similique, assumenda molestiae maiores cupiditate! Tempore repellat minima facere repellendus distinctio soluta aut magni velit nostrum nisi assumenda, quaerat quisquam officia nihil voluptatum, culpa, illo dolore obcaecati quos dolores esse blanditiis voluptatem nam! Voluptates unde eius consequuntur, est dicta ullam iste commodi temporibus! Consequuntur, numquam. Tempora, culpa repudiandae ipsa earum magnam animi. Enim facere commodi harum ipsam quos fugit earum amet temporibus voluptas voluptatibus, tenetur ducimus, alias, nam saepe hic id pariatur labore veritatis maiores optio ipsa aliquam consectetur porro est. Aut iusto atque labore! Fugit alias eligendi eveniet omnis nesciunt dolorum mollitia aut at ducimus, aliquid delectus minima non officiis natus sed repellat aliquam pariatur voluptatum cupiditate incidunt ad et dignissimos. Reprehenderit, corporis veritatis fugit ab alias perferendis repellat aspernatur ea dolorem ratione officiis. Molestiae veniam assumenda tenetur non voluptatum iste magni nemo!',
                'blog_subcategory_is_active'         => '1',
                'blog_subcategory_slug'              => '/blog/subcategory/1/all-written-articles',
                'created_at'                         => '2021-09-01 00:00:00',
                'updated_at'                         => '2021-09-01 00:00:00',
            ],
            [
                'id'                                 => '2',
                'blog_category_id'                   => '1',
                'blog_subcategory_title'             => 'Subcategoria B',
                'blog_subcategory_short_description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet accusantium rerum impedit nam, voluptate reprehenderit nemo expedita fuga, dicta sint eum ex delectus saepe debitis veniam recusandae perferendis illum optio!',
                'blog_subcategory_description'       => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius corporis velit enim animi. Reiciendis nesciunt libero magnam quaerat! Nulla, dolore sint deserunt quas iure sed magnam consectetur architecto eligendi iste? Dignissimos, velit, molestiae repellendus cupiditate nobis eos corporis ipsam possimus qui unde veritatis temporibus, dolorum saepe accusamus laudantium quibusdam iusto autem placeat eaque error quia provident dolore laboriosam minus? Fugit corrupti nam ex, officia sapiente aspernatur eos at suscipit eveniet quasi quisquam ea fugiat reprehenderit provident. Minima, laudantium exercitationem ducimus ratione natus tempore! Asperiores, consequuntur! Ad culpa nihil nemo magni iste, deserunt quis? Esse quia totam ea magni quas ipsam cumque minus officiis unde quos sapiente laboriosam debitis iste reiciendis beatae ut vel perspiciatis quisquam aperiam similique, assumenda molestiae maiores cupiditate! Tempore repellat minima facere repellendus distinctio soluta aut magni velit nostrum nisi assumenda, quaerat quisquam officia nihil voluptatum, culpa, illo dolore obcaecati quos dolores esse blanditiis voluptatem nam! Voluptates unde eius consequuntur, est dicta ullam iste commodi temporibus! Consequuntur, numquam. Tempora, culpa repudiandae ipsa earum magnam animi. Enim facere commodi harum ipsam quos fugit earum amet temporibus voluptas voluptatibus, tenetur ducimus, alias, nam saepe hic id pariatur labore veritatis maiores optio ipsa aliquam consectetur porro est. Aut iusto atque labore! Fugit alias eligendi eveniet omnis nesciunt dolorum mollitia aut at ducimus, aliquid delectus minima non officiis natus sed repellat aliquam pariatur voluptatum cupiditate incidunt ad et dignissimos. Reprehenderit, corporis veritatis fugit ab alias perferendis repellat aspernatur ea dolorem ratione officiis. Molestiae veniam assumenda tenetur non voluptatum iste magni nemo!',
                'blog_subcategory_is_active'         => '1',
                'blog_subcategory_slug'              => '/blog/subcategory/2/all-written-articles',
                'created_at'                         => '2021-09-01 00:00:00',
                'updated_at'                         => '2021-09-01 00:00:00',
            ],
            [
                'id'                                 => '3',
                'blog_category_id'                   => '1',
                'blog_subcategory_title'             => 'Subcategoria C',
                'blog_subcategory_short_description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet accusantium rerum impedit nam, voluptate reprehenderit nemo expedita fuga, dicta sint eum ex delectus saepe debitis veniam recusandae perferendis illum optio!',
                'blog_subcategory_description'       => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius corporis velit enim animi. Reiciendis nesciunt libero magnam quaerat! Nulla, dolore sint deserunt quas iure sed magnam consectetur architecto eligendi iste? Dignissimos, velit, molestiae repellendus cupiditate nobis eos corporis ipsam possimus qui unde veritatis temporibus, dolorum saepe accusamus laudantium quibusdam iusto autem placeat eaque error quia provident dolore laboriosam minus? Fugit corrupti nam ex, officia sapiente aspernatur eos at suscipit eveniet quasi quisquam ea fugiat reprehenderit provident. Minima, laudantium exercitationem ducimus ratione natus tempore! Asperiores, consequuntur! Ad culpa nihil nemo magni iste, deserunt quis? Esse quia totam ea magni quas ipsam cumque minus officiis unde quos sapiente laboriosam debitis iste reiciendis beatae ut vel perspiciatis quisquam aperiam similique, assumenda molestiae maiores cupiditate! Tempore repellat minima facere repellendus distinctio soluta aut magni velit nostrum nisi assumenda, quaerat quisquam officia nihil voluptatum, culpa, illo dolore obcaecati quos dolores esse blanditiis voluptatem nam! Voluptates unde eius consequuntur, est dicta ullam iste commodi temporibus! Consequuntur, numquam. Tempora, culpa repudiandae ipsa earum magnam animi. Enim facere commodi harum ipsam quos fugit earum amet temporibus voluptas voluptatibus, tenetur ducimus, alias, nam saepe hic id pariatur labore veritatis maiores optio ipsa aliquam consectetur porro est. Aut iusto atque labore! Fugit alias eligendi eveniet omnis nesciunt dolorum mollitia aut at ducimus, aliquid delectus minima non officiis natus sed repellat aliquam pariatur voluptatum cupiditate incidunt ad et dignissimos. Reprehenderit, corporis veritatis fugit ab alias perferendis repellat aspernatur ea dolorem ratione officiis. Molestiae veniam assumenda tenetur non voluptatum iste magni nemo!',
                'blog_subcategory_is_active'         => '1',
                'blog_subcategory_slug'              => '/blog/subcategory/3/all-written-articles',
                'created_at'                         => '2021-09-01 00:00:00',
                'updated_at'                         => '2021-09-01 00:00:00',
            ],
            [
                'id'                                 => '4',
                'blog_category_id'                   => '1',
                'blog_subcategory_title'             => 'Subcategoria D',
                'blog_subcategory_short_description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet accusantium rerum impedit nam, voluptate reprehenderit nemo expedita fuga, dicta sint eum ex delectus saepe debitis veniam recusandae perferendis illum optio!',
                'blog_subcategory_description'       => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius corporis velit enim animi. Reiciendis nesciunt libero magnam quaerat! Nulla, dolore sint deserunt quas iure sed magnam consectetur architecto eligendi iste? Dignissimos, velit, molestiae repellendus cupiditate nobis eos corporis ipsam possimus qui unde veritatis temporibus, dolorum saepe accusamus laudantium quibusdam iusto autem placeat eaque error quia provident dolore laboriosam minus? Fugit corrupti nam ex, officia sapiente aspernatur eos at suscipit eveniet quasi quisquam ea fugiat reprehenderit provident. Minima, laudantium exercitationem ducimus ratione natus tempore! Asperiores, consequuntur! Ad culpa nihil nemo magni iste, deserunt quis? Esse quia totam ea magni quas ipsam cumque minus officiis unde quos sapiente laboriosam debitis iste reiciendis beatae ut vel perspiciatis quisquam aperiam similique, assumenda molestiae maiores cupiditate! Tempore repellat minima facere repellendus distinctio soluta aut magni velit nostrum nisi assumenda, quaerat quisquam officia nihil voluptatum, culpa, illo dolore obcaecati quos dolores esse blanditiis voluptatem nam! Voluptates unde eius consequuntur, est dicta ullam iste commodi temporibus! Consequuntur, numquam. Tempora, culpa repudiandae ipsa earum magnam animi. Enim facere commodi harum ipsam quos fugit earum amet temporibus voluptas voluptatibus, tenetur ducimus, alias, nam saepe hic id pariatur labore veritatis maiores optio ipsa aliquam consectetur porro est. Aut iusto atque labore! Fugit alias eligendi eveniet omnis nesciunt dolorum mollitia aut at ducimus, aliquid delectus minima non officiis natus sed repellat aliquam pariatur voluptatum cupiditate incidunt ad et dignissimos. Reprehenderit, corporis veritatis fugit ab alias perferendis repellat aspernatur ea dolorem ratione officiis. Molestiae veniam assumenda tenetur non voluptatum iste magni nemo!',
                'blog_subcategory_is_active'         => '0',
                'blog_subcategory_slug'              => '/blog/subcategory/4/all-written-articles',
                'created_at'                         => '2021-09-01 00:00:00',
                'updated_at'                         => '2021-09-01 00:00:00',
            ],
            [
                'id'                                 => '5',
                'blog_category_id'                   => '2',
                'blog_subcategory_title'             => 'Subcategoria A',
                'blog_subcategory_short_description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet accusantium rerum impedit nam, voluptate reprehenderit nemo expedita fuga, dicta sint eum ex delectus saepe debitis veniam recusandae perferendis illum optio!',
                'blog_subcategory_description'       => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius corporis velit enim animi. Reiciendis nesciunt libero magnam quaerat! Nulla, dolore sint deserunt quas iure sed magnam consectetur architecto eligendi iste? Dignissimos, velit, molestiae repellendus cupiditate nobis eos corporis ipsam possimus qui unde veritatis temporibus, dolorum saepe accusamus laudantium quibusdam iusto autem placeat eaque error quia provident dolore laboriosam minus? Fugit corrupti nam ex, officia sapiente aspernatur eos at suscipit eveniet quasi quisquam ea fugiat reprehenderit provident. Minima, laudantium exercitationem ducimus ratione natus tempore! Asperiores, consequuntur! Ad culpa nihil nemo magni iste, deserunt quis? Esse quia totam ea magni quas ipsam cumque minus officiis unde quos sapiente laboriosam debitis iste reiciendis beatae ut vel perspiciatis quisquam aperiam similique, assumenda molestiae maiores cupiditate! Tempore repellat minima facere repellendus distinctio soluta aut magni velit nostrum nisi assumenda, quaerat quisquam officia nihil voluptatum, culpa, illo dolore obcaecati quos dolores esse blanditiis voluptatem nam! Voluptates unde eius consequuntur, est dicta ullam iste commodi temporibus! Consequuntur, numquam. Tempora, culpa repudiandae ipsa earum magnam animi. Enim facere commodi harum ipsam quos fugit earum amet temporibus voluptas voluptatibus, tenetur ducimus, alias, nam saepe hic id pariatur labore veritatis maiores optio ipsa aliquam consectetur porro est. Aut iusto atque labore! Fugit alias eligendi eveniet omnis nesciunt dolorum mollitia aut at ducimus, aliquid delectus minima non officiis natus sed repellat aliquam pariatur voluptatum cupiditate incidunt ad et dignissimos. Reprehenderit, corporis veritatis fugit ab alias perferendis repellat aspernatur ea dolorem ratione officiis. Molestiae veniam assumenda tenetur non voluptatum iste magni nemo!',
                'blog_subcategory_is_active'         => '1',
                'blog_subcategory_slug'              => '/blog/subcategory/5/all-audio-articles',
                'created_at'                         => '2021-09-01 00:00:00',
                'updated_at'                         => '2021-09-01 00:00:00',
            ],
            [
                'id'                                 => '6',
                'blog_category_id'                   => '2',
                'blog_subcategory_title'             => 'Subcategoria B',
                'blog_subcategory_short_description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet accusantium rerum impedit nam, voluptate reprehenderit nemo expedita fuga, dicta sint eum ex delectus saepe debitis veniam recusandae perferendis illum optio!',
                'blog_subcategory_description'       => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius corporis velit enim animi. Reiciendis nesciunt libero magnam quaerat! Nulla, dolore sint deserunt quas iure sed magnam consectetur architecto eligendi iste? Dignissimos, velit, molestiae repellendus cupiditate nobis eos corporis ipsam possimus qui unde veritatis temporibus, dolorum saepe accusamus laudantium quibusdam iusto autem placeat eaque error quia provident dolore laboriosam minus? Fugit corrupti nam ex, officia sapiente aspernatur eos at suscipit eveniet quasi quisquam ea fugiat reprehenderit provident. Minima, laudantium exercitationem ducimus ratione natus tempore! Asperiores, consequuntur! Ad culpa nihil nemo magni iste, deserunt quis? Esse quia totam ea magni quas ipsam cumque minus officiis unde quos sapiente laboriosam debitis iste reiciendis beatae ut vel perspiciatis quisquam aperiam similique, assumenda molestiae maiores cupiditate! Tempore repellat minima facere repellendus distinctio soluta aut magni velit nostrum nisi assumenda, quaerat quisquam officia nihil voluptatum, culpa, illo dolore obcaecati quos dolores esse blanditiis voluptatem nam! Voluptates unde eius consequuntur, est dicta ullam iste commodi temporibus! Consequuntur, numquam. Tempora, culpa repudiandae ipsa earum magnam animi. Enim facere commodi harum ipsam quos fugit earum amet temporibus voluptas voluptatibus, tenetur ducimus, alias, nam saepe hic id pariatur labore veritatis maiores optio ipsa aliquam consectetur porro est. Aut iusto atque labore! Fugit alias eligendi eveniet omnis nesciunt dolorum mollitia aut at ducimus, aliquid delectus minima non officiis natus sed repellat aliquam pariatur voluptatum cupiditate incidunt ad et dignissimos. Reprehenderit, corporis veritatis fugit ab alias perferendis repellat aspernatur ea dolorem ratione officiis. Molestiae veniam assumenda tenetur non voluptatum iste magni nemo!',
                'blog_subcategory_is_active'         => '1',
                'blog_subcategory_slug'              => '/blog/subcategory/6/all-audio-articles',
                'created_at'                         => '2021-09-01 00:00:00',
                'updated_at'                         => '2021-09-01 00:00:00',
            ],
            [
                'id'                                 => '7',
                'blog_category_id'                   => '2',
                'blog_subcategory_title'             => 'Subcategoria C',
                'blog_subcategory_short_description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet accusantium rerum impedit nam, voluptate reprehenderit nemo expedita fuga, dicta sint eum ex delectus saepe debitis veniam recusandae perferendis illum optio!',
                'blog_subcategory_description'       => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius corporis velit enim animi. Reiciendis nesciunt libero magnam quaerat! Nulla, dolore sint deserunt quas iure sed magnam consectetur architecto eligendi iste? Dignissimos, velit, molestiae repellendus cupiditate nobis eos corporis ipsam possimus qui unde veritatis temporibus, dolorum saepe accusamus laudantium quibusdam iusto autem placeat eaque error quia provident dolore laboriosam minus? Fugit corrupti nam ex, officia sapiente aspernatur eos at suscipit eveniet quasi quisquam ea fugiat reprehenderit provident. Minima, laudantium exercitationem ducimus ratione natus tempore! Asperiores, consequuntur! Ad culpa nihil nemo magni iste, deserunt quis? Esse quia totam ea magni quas ipsam cumque minus officiis unde quos sapiente laboriosam debitis iste reiciendis beatae ut vel perspiciatis quisquam aperiam similique, assumenda molestiae maiores cupiditate! Tempore repellat minima facere repellendus distinctio soluta aut magni velit nostrum nisi assumenda, quaerat quisquam officia nihil voluptatum, culpa, illo dolore obcaecati quos dolores esse blanditiis voluptatem nam! Voluptates unde eius consequuntur, est dicta ullam iste commodi temporibus! Consequuntur, numquam. Tempora, culpa repudiandae ipsa earum magnam animi. Enim facere commodi harum ipsam quos fugit earum amet temporibus voluptas voluptatibus, tenetur ducimus, alias, nam saepe hic id pariatur labore veritatis maiores optio ipsa aliquam consectetur porro est. Aut iusto atque labore! Fugit alias eligendi eveniet omnis nesciunt dolorum mollitia aut at ducimus, aliquid delectus minima non officiis natus sed repellat aliquam pariatur voluptatum cupiditate incidunt ad et dignissimos. Reprehenderit, corporis veritatis fugit ab alias perferendis repellat aspernatur ea dolorem ratione officiis. Molestiae veniam assumenda tenetur non voluptatum iste magni nemo!',
                'blog_subcategory_is_active'         => '1',
                'blog_subcategory_slug'              => '/blog/subcategory/7/all-audio-articles',
                'created_at'                         => '2021-09-01 00:00:00',
                'updated_at'                         => '2021-09-01 00:00:00',
            ],
            [
                'id'                                 => '8',
                'blog_category_id'                   => '3',
                'blog_subcategory_title'             => 'Subcategoria A',
                'blog_subcategory_short_description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet accusantium rerum impedit nam, voluptate reprehenderit nemo expedita fuga, dicta sint eum ex delectus saepe debitis veniam recusandae perferendis illum optio!',
                'blog_subcategory_description'       => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius corporis velit enim animi. Reiciendis nesciunt libero magnam quaerat! Nulla, dolore sint deserunt quas iure sed magnam consectetur architecto eligendi iste? Dignissimos, velit, molestiae repellendus cupiditate nobis eos corporis ipsam possimus qui unde veritatis temporibus, dolorum saepe accusamus laudantium quibusdam iusto autem placeat eaque error quia provident dolore laboriosam minus? Fugit corrupti nam ex, officia sapiente aspernatur eos at suscipit eveniet quasi quisquam ea fugiat reprehenderit provident. Minima, laudantium exercitationem ducimus ratione natus tempore! Asperiores, consequuntur! Ad culpa nihil nemo magni iste, deserunt quis? Esse quia totam ea magni quas ipsam cumque minus officiis unde quos sapiente laboriosam debitis iste reiciendis beatae ut vel perspiciatis quisquam aperiam similique, assumenda molestiae maiores cupiditate! Tempore repellat minima facere repellendus distinctio soluta aut magni velit nostrum nisi assumenda, quaerat quisquam officia nihil voluptatum, culpa, illo dolore obcaecati quos dolores esse blanditiis voluptatem nam! Voluptates unde eius consequuntur, est dicta ullam iste commodi temporibus! Consequuntur, numquam. Tempora, culpa repudiandae ipsa earum magnam animi. Enim facere commodi harum ipsam quos fugit earum amet temporibus voluptas voluptatibus, tenetur ducimus, alias, nam saepe hic id pariatur labore veritatis maiores optio ipsa aliquam consectetur porro est. Aut iusto atque labore! Fugit alias eligendi eveniet omnis nesciunt dolorum mollitia aut at ducimus, aliquid delectus minima non officiis natus sed repellat aliquam pariatur voluptatum cupiditate incidunt ad et dignissimos. Reprehenderit, corporis veritatis fugit ab alias perferendis repellat aspernatur ea dolorem ratione officiis. Molestiae veniam assumenda tenetur non voluptatum iste magni nemo!',
                'blog_subcategory_is_active'         => '1',
                'blog_subcategory_slug'              => '/blog/subcategory/8/all-video-articles',
                'created_at'                         => '2021-09-01 00:00:00',
                'updated_at'                         => '2021-09-01 00:00:00',
            ],
            [
                'id'                                 => '9',
                'blog_category_id'                   => '3',
                'blog_subcategory_title'             => 'Subcategoria B',
                'blog_subcategory_short_description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet accusantium rerum impedit nam, voluptate reprehenderit nemo expedita fuga, dicta sint eum ex delectus saepe debitis veniam recusandae perferendis illum optio!',
                'blog_subcategory_description'       => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius corporis velit enim animi. Reiciendis nesciunt libero magnam quaerat! Nulla, dolore sint deserunt quas iure sed magnam consectetur architecto eligendi iste? Dignissimos, velit, molestiae repellendus cupiditate nobis eos corporis ipsam possimus qui unde veritatis temporibus, dolorum saepe accusamus laudantium quibusdam iusto autem placeat eaque error quia provident dolore laboriosam minus? Fugit corrupti nam ex, officia sapiente aspernatur eos at suscipit eveniet quasi quisquam ea fugiat reprehenderit provident. Minima, laudantium exercitationem ducimus ratione natus tempore! Asperiores, consequuntur! Ad culpa nihil nemo magni iste, deserunt quis? Esse quia totam ea magni quas ipsam cumque minus officiis unde quos sapiente laboriosam debitis iste reiciendis beatae ut vel perspiciatis quisquam aperiam similique, assumenda molestiae maiores cupiditate! Tempore repellat minima facere repellendus distinctio soluta aut magni velit nostrum nisi assumenda, quaerat quisquam officia nihil voluptatum, culpa, illo dolore obcaecati quos dolores esse blanditiis voluptatem nam! Voluptates unde eius consequuntur, est dicta ullam iste commodi temporibus! Consequuntur, numquam. Tempora, culpa repudiandae ipsa earum magnam animi. Enim facere commodi harum ipsam quos fugit earum amet temporibus voluptas voluptatibus, tenetur ducimus, alias, nam saepe hic id pariatur labore veritatis maiores optio ipsa aliquam consectetur porro est. Aut iusto atque labore! Fugit alias eligendi eveniet omnis nesciunt dolorum mollitia aut at ducimus, aliquid delectus minima non officiis natus sed repellat aliquam pariatur voluptatum cupiditate incidunt ad et dignissimos. Reprehenderit, corporis veritatis fugit ab alias perferendis repellat aspernatur ea dolorem ratione officiis. Molestiae veniam assumenda tenetur non voluptatum iste magni nemo!',
                'blog_subcategory_is_active'         => '1',
                'blog_subcategory_slug'              => '/blog/subcategory/9/all-video-articles',
                'created_at'                         => '2021-09-01 00:00:00',
                'updated_at'                         => '2021-09-01 00:00:00',
            ],
            [
                'id'                                 => '10',
                'blog_category_id'                   => '3',
                'blog_subcategory_title'             => 'Subcategoria C',
                'blog_subcategory_short_description' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet accusantium rerum impedit nam, voluptate reprehenderit nemo expedita fuga, dicta sint eum ex delectus saepe debitis veniam recusandae perferendis illum optio!',
                'blog_subcategory_description'       => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius corporis velit enim animi. Reiciendis nesciunt libero magnam quaerat! Nulla, dolore sint deserunt quas iure sed magnam consectetur architecto eligendi iste? Dignissimos, velit, molestiae repellendus cupiditate nobis eos corporis ipsam possimus qui unde veritatis temporibus, dolorum saepe accusamus laudantium quibusdam iusto autem placeat eaque error quia provident dolore laboriosam minus? Fugit corrupti nam ex, officia sapiente aspernatur eos at suscipit eveniet quasi quisquam ea fugiat reprehenderit provident. Minima, laudantium exercitationem ducimus ratione natus tempore! Asperiores, consequuntur! Ad culpa nihil nemo magni iste, deserunt quis? Esse quia totam ea magni quas ipsam cumque minus officiis unde quos sapiente laboriosam debitis iste reiciendis beatae ut vel perspiciatis quisquam aperiam similique, assumenda molestiae maiores cupiditate! Tempore repellat minima facere repellendus distinctio soluta aut magni velit nostrum nisi assumenda, quaerat quisquam officia nihil voluptatum, culpa, illo dolore obcaecati quos dolores esse blanditiis voluptatem nam! Voluptates unde eius consequuntur, est dicta ullam iste commodi temporibus! Consequuntur, numquam. Tempora, culpa repudiandae ipsa earum magnam animi. Enim facere commodi harum ipsam quos fugit earum amet temporibus voluptas voluptatibus, tenetur ducimus, alias, nam saepe hic id pariatur labore veritatis maiores optio ipsa aliquam consectetur porro est. Aut iusto atque labore! Fugit alias eligendi eveniet omnis nesciunt dolorum mollitia aut at ducimus, aliquid delectus minima non officiis natus sed repellat aliquam pariatur voluptatum cupiditate incidunt ad et dignissimos. Reprehenderit, corporis veritatis fugit ab alias perferendis repellat aspernatur ea dolorem ratione officiis. Molestiae veniam assumenda tenetur non voluptatum iste magni nemo!',
                'blog_subcategory_is_active'         => '1',
                'blog_subcategory_slug'              => '/blog/subcategory/10/all-video-articles',
                'created_at'                         => '2021-09-01 00:00:00',
                'updated_at'                         => '2021-09-01 00:00:00',
            ],
        ];
        BlogSubcategory::insert($records);
    }
}
